### ISSUE TITLE
ccdproc fails with error "operand units do not match"

### ISSUE THREAD

**Issue by mrkite92** [astropy/ccdproc#361]
[Archive.zip](https://github.com/astropy/ccdproc/files/321651/Archive.zip)

Hi ccdproc gurus,

I work on Mac with latest version of OS and Python 2.7 ressources linked to ccdproc. I wrote a short script to deflat a few images, and I got:

Traceback (most recent call last):
  File "deflat.py", line 34, in <module>
    data_exposure = img_expos)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/ccdproc/log_meta.py", line 68, in wrapper
    result = func(*args, **kwd)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/ccdproc/core.py", line 208, in ccd_process
    nccd = nccd.subtract(master_bias)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/ccdproc/ccddata.py", line 444, in subtract
    result = super(CCDData, self).subtract(other)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/astropy/nddata/mixins/ndarithmetic.py", line 215, in subtract
    operand, propagate_uncertainties, "subtraction", np.subtract)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/astropy/nddata/mixins/ndarithmetic.py", line 87, in _arithmetic
    raise ValueError("operand units do not match")
ValueError: operand units do not match

After digging into the code, I strongly suspect the value of the gain (2.35 electrons/adu) not be to properly applied. In line 349 of ccddata.py, the unit to be used (result_unit) is 'electron'. Then, in function subtract, line 433, other and self have different units. I attach here my script (dir_wrk to be modified) and relevant images.

**Comment by mwcraig** [comment]
@mrkite92 -- thanks for the report, I'll take a look on Monday.

**Comment by mwcraig** [comment]
Could you please let me know what version of astropy and ccdproc you are using?

**Comment by mrkite92** [comment]
Hi Matt,

My ccdproc is 1.0.1, and astropy is 1.1.2

Cheers,
JB

**Comment by mwcraig** [comment]
@mrkite92, finally got around to looking at this today. The issue, as far as I can tell, is that `ccd_process` expects the `master_bias`, etc., to have already been gain corrected. In other words, in `ccd_process` the image you are reducing is multiplied by the gain, but the master images you pass in are not. 

The result is that when `ccd_process` tries to subtract the bias it is taking the difference of the image you are operating on (`img_hdu[0]`) after the gain is applied, so that it is in units of `electron`, but the bias is still in `adu`, leading to the error.

Would it be helpful to clarify this behavior in the documentation or maybe even check for it and raise a clearer error?

**Comment by mrkite92** [comment]
Hi Matt,

Thanks for this report. I think that both options should be very useful!

Cheers,
JB
