### ISSUE TITLE
ValueError when compiling

### ISSUE THREAD

**Issue by dagnic** [astropy/ccdproc#397]
Hello everybody, 

I'm a new user and I face a first problem with following line: 

```
folder = '/home/.....'
ic1 = ImageFileCollection(folder, keywords=['imagetyp', 'object', 'filter'])
my_files = ic1.files_filtered(filter='halpha', imagetyp='Light Frame')
images = []

for i in range(len(my_files)):
    images.append(ccdproc.CCDData(folder+my_files[i], unit=u.adu))
ccdproc.combine(images, 'res.fit')
```

which gave me:

```

INFO:astropy:splitting each image into 1 chunks to limit memory usage to 16000000000.0 bytes.
Traceback (most recent call last):
  File "/home/........./process.py", line 20, in <module>
    ccdproc.combine(images, 'res.fit')
  File "/home/nicolas/.local/lib/python2.7/site-packages/ccdproc/combiner.py", line 582, in combine
    xs, ys = ccd.data.shape
ValueError: need more than 0 values to unpack
```

I'm using  last version of ccdproc and astropy from pip. 

Thanks for help,
Nicolas

**Comment by MSeifert04** [comment]
@dagnic Thank you for the report. To exclude some possible (not ccdproc related errors) could you please run:

```
folder = '/home/.....'
ic1 = ImageFileCollection(folder, keywords=['imagetyp', 'object', 'filter'])
my_files = ic1.files_filtered(filter='halpha', imagetyp='Light Frame')
images = []

import astropy
import ccdproc
print(astropy.__version__)
print(ccdproc.__version__)
print(my_files)
for filename in my_files:
    images.append(ccdproc.CCDData(folder+filename, unit=u.adu))
print([ccd.shape for ccd in images])
```
and say what these `print` statements print?

**Comment by dagnic** [comment]
Here is the result:

```
astropy.__version__ = 1.2.1
ccdproc.__version__ = 1.1.0

```
for [ccd.shape for ccd in images], I get a list (*16) containing same values (1472, 2184)

**Comment by dagnic** [comment]
In fact, replacing:
```
 for i in range(len(my_files)):
     images.append(ccdproc.CCDData(folder+my_files[i], unit=u.adu))
```

with:
```
for filename in my_files:
    images.append(ccdproc.CCDData.read(folder+filename, unit=u.adu))
```
solves the problem. In this case I just get following warnings:
```
INFO: splitting each image into 1 chunks to limit memory usage to 16000000000.0 bytes. [ccdproc.combiner]
WARNING: VerifyWarning: Keyword name 'trim_image' is greater than 8 characters or contains characters not allowed by the FITS standard; a HIERARCH card will be created. [astropy.io.fits.card]
WARNING:astropy:VerifyWarning: Keyword name 'trim_image' is greater than 8 characters or contains characters not allowed by the FITS standard; a HIERARCH card will be created.
```

**Comment by mwcraig** [comment]
@dagnic -- those warnings are normal. I'm not sure why your original loop failed.

As a new user of ccdproc, would it be helpful if we suppressed those warnings?

**Comment by mwcraig** [comment]
Oops, I do see the issue with the original loop -- you omitted the `read` from CCDData.read`.
