### ISSUE TITLE
Importing with astropy v4.0 

### ISSUE THREAD

**Issue by simontorres** [astropy/ccdproc#724]
I manage two packages that use astropy and ccdproc. They have automated testing running daily on a Jenkins server. After the astropy version 4.0 became the default on astroconda these tests started failing at import. I had the ccdproc version fixed at `1.3.0.post1` because later versions had problems that I may or may not have reported. So, the reason why the test are failing are because importing `six` from `astropy.extern.six` has been deprecated which exactly happened in version `1.3.0.post1`. Now I have **updated** to version `2.1.0` and still requires `astropy.extern.six`

```
+ conda env create -q python=3.8 -f environment.yml
Collecting package metadata (repodata.json): ...working... done
Solving environment: ...working... done
Preparing transaction: ...working... done
Verifying transaction: ...working... done
Executing transaction: ...working... done
+ source activate goodman_focus
++ _CONDA_ROOT=/home/jenkins/miniconda
++ . /home/jenkins/miniconda/etc/profile.d/conda.sh
+++ export CONDA_EXE=/home/jenkins/miniconda/bin/conda
+++ CONDA_EXE=/home/jenkins/miniconda/bin/conda
+++ export _CE_M=
+++ _CE_M=
+++ export _CE_CONDA=
+++ _CE_CONDA=
+++ export CONDA_PYTHON_EXE=/home/jenkins/miniconda/bin/python
+++ CONDA_PYTHON_EXE=/home/jenkins/miniconda/bin/python
+++ '[' -z '' ']'
+++ export CONDA_SHLVL=0
+++ CONDA_SHLVL=0
+++ '[' -n x ']'
+++ '[' -n '' ']'
+++++ dirname /home/jenkins/miniconda/bin/conda
++++ dirname /home/jenkins/miniconda/bin
+++ PATH=/home/jenkins/miniconda/condabin:/home/jenkins/miniconda/bin:/sbin:/usr/sbin:/bin:/usr/bin
+++ export PATH
+++ '[' -z '' ']'
+++ PS1=
++ conda activate goodman_focus
++ '[' 2 -lt 1 ']'
++ local cmd=activate
++ shift
++ case "$cmd" in
++ __conda_activate activate goodman_focus
++ '[' -n '' ']'
++ local cmd=activate
++ shift
++ local ask_conda
++ CONDA_INTERNAL_OLDPATH=/home/jenkins/miniconda/condabin:/home/jenkins/miniconda/bin:/sbin:/usr/sbin:/bin:/usr/bin
++ __add_sys_prefix_to_path
++ '[' -n '' ']'
+++ dirname /home/jenkins/miniconda/bin/conda
++ SYSP=/home/jenkins/miniconda/bin
+++ dirname /home/jenkins/miniconda/bin
++ SYSP=/home/jenkins/miniconda
++ '[' -n '' ']'
++ PATH=/home/jenkins/miniconda/bin:/home/jenkins/miniconda/condabin:/home/jenkins/miniconda/bin:/sbin:/usr/sbin:/bin:/usr/bin
++ export PATH
+++ PS1=
+++ /home/jenkins/miniconda/bin/conda shell.posix activate goodman_focus
++ ask_conda='export PATH='\''/home/jenkins/miniconda/envs/goodman_focus/bin:/home/jenkins/miniconda/condabin:/home/jenkins/miniconda/bin:/sbin:/usr/sbin:/bin:/usr/bin'\''
export CONDA_PREFIX='\''/home/jenkins/miniconda/envs/goodman_focus'\''
export CONDA_SHLVL='\''1'\''
export CONDA_DEFAULT_ENV='\''goodman_focus'\''
export CONDA_PROMPT_MODIFIER='\'''\''
export CONDA_EXE='\''/home/jenkins/miniconda/bin/conda'\''
export _CE_M='\'''\''
export _CE_CONDA='\'''\''
export CONDA_PYTHON_EXE='\''/home/jenkins/miniconda/bin/python'\'''
++ rc=0
++ PATH=/home/jenkins/miniconda/condabin:/home/jenkins/miniconda/bin:/sbin:/usr/sbin:/bin:/usr/bin
++ eval 'export PATH='\''/home/jenkins/miniconda/envs/goodman_focus/bin:/home/jenkins/miniconda/condabin:/home/jenkins/miniconda/bin:/sbin:/usr/sbin:/bin:/usr/bin'\''
export CONDA_PREFIX='\''/home/jenkins/miniconda/envs/goodman_focus'\''
export CONDA_SHLVL='\''1'\''
export CONDA_DEFAULT_ENV='\''goodman_focus'\''
export CONDA_PROMPT_MODIFIER='\'''\''
export CONDA_EXE='\''/home/jenkins/miniconda/bin/conda'\''
export _CE_M='\'''\''
export _CE_CONDA='\'''\''
export CONDA_PYTHON_EXE='\''/home/jenkins/miniconda/bin/python'\'''
+++ export PATH=/home/jenkins/miniconda/envs/goodman_focus/bin:/home/jenkins/miniconda/condabin:/home/jenkins/miniconda/bin:/sbin:/usr/sbin:/bin:/usr/bin
+++ PATH=/home/jenkins/miniconda/envs/goodman_focus/bin:/home/jenkins/miniconda/condabin:/home/jenkins/miniconda/bin:/sbin:/usr/sbin:/bin:/usr/bin
+++ export CONDA_PREFIX=/home/jenkins/miniconda/envs/goodman_focus
+++ CONDA_PREFIX=/home/jenkins/miniconda/envs/goodman_focus
+++ export CONDA_SHLVL=1
+++ CONDA_SHLVL=1
+++ export CONDA_DEFAULT_ENV=goodman_focus
+++ CONDA_DEFAULT_ENV=goodman_focus
+++ export CONDA_PROMPT_MODIFIER=
+++ CONDA_PROMPT_MODIFIER=
+++ export CONDA_EXE=/home/jenkins/miniconda/bin/conda
+++ CONDA_EXE=/home/jenkins/miniconda/bin/conda
+++ export _CE_M=
+++ _CE_M=
+++ export _CE_CONDA=
+++ _CE_CONDA=
+++ export CONDA_PYTHON_EXE=/home/jenkins/miniconda/bin/python
+++ CONDA_PYTHON_EXE=/home/jenkins/miniconda/bin/python
++ '[' 0 '!=' 0 ']'
++ __conda_hashr
++ '[' -n '' ']'
++ '[' -n '' ']'
++ hash -r
+ python setup.py test
running test
WARNING: Testing via this command is deprecated and will be removed in a future version. Users looking for a generic test entry point independent of test runner are encouraged to use tox.
running egg_info
creating goodman_focus.egg-info
writing goodman_focus.egg-info/PKG-INFO
writing dependency_links to goodman_focus.egg-info/dependency_links.txt
writing entry points to goodman_focus.egg-info/entry_points.txt
writing requirements to goodman_focus.egg-info/requires.txt
writing top-level names to goodman_focus.egg-info/top_level.txt
writing manifest file 'goodman_focus.egg-info/SOURCES.txt'
reading manifest file 'goodman_focus.egg-info/SOURCES.txt'
writing manifest file 'goodman_focus.egg-info/SOURCES.txt'
running build_ext
goodman_focus (unittest.loader._FailedTest) ... ERROR
test_goodman_focus (unittest.loader._FailedTest) ... ERROR
goodman_focus.tests.test_goodman_focus (unittest.loader._FailedTest) ... ERROR

======================================================================
ERROR: goodman_focus (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: goodman_focus
Traceback (most recent call last):
  File "/home/jenkins/miniconda/envs/goodman_focus/lib/python3.7/unittest/loader.py", line 154, in loadTestsFromName
    module = __import__(module_name)
  File "/var/lib/jenkins/workspace/GoodmanFocus/goodman_focus/goodman_focus.py", line 13, in <module>
    from ccdproc import CCDData
  File "/home/jenkins/miniconda/envs/goodman_focus/lib/python3.7/site-packages/ccdproc/__init__.py", line 16, in <module>
    from .core import *
  File "/home/jenkins/miniconda/envs/goodman_focus/lib/python3.7/site-packages/ccdproc/core.py", line 12, in <module>
    from astropy.extern import six
ImportError: cannot import name 'six' from 'astropy.extern' (/home/jenkins/miniconda/envs/goodman_focus/lib/python3.7/site-packages/astropy/extern/__init__.py)


======================================================================
ERROR: test_goodman_focus (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: test_goodman_focus
Traceback (most recent call last):
  File "/home/jenkins/miniconda/envs/goodman_focus/lib/python3.7/unittest/loader.py", line 154, in loadTestsFromName
    module = __import__(module_name)
  File "/var/lib/jenkins/workspace/GoodmanFocus/goodman_focus/tests/test_goodman_focus.py", line 9, in <module>
    from ccdproc import CCDData
  File "/home/jenkins/miniconda/envs/goodman_focus/lib/python3.7/site-packages/ccdproc/__init__.py", line 16, in <module>
    from .core import *
  File "/home/jenkins/miniconda/envs/goodman_focus/lib/python3.7/site-packages/ccdproc/core.py", line 12, in <module>
    from astropy.extern import six
ImportError: cannot import name 'six' from 'astropy.extern' (/home/jenkins/miniconda/envs/goodman_focus/lib/python3.7/site-packages/astropy/extern/__init__.py)


======================================================================
ERROR: goodman_focus.tests.test_goodman_focus (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: goodman_focus.tests.test_goodman_focus
Traceback (most recent call last):
  File "/home/jenkins/miniconda/envs/goodman_focus/lib/python3.7/unittest/loader.py", line 436, in _find_test_path
    module = self._get_module_from_name(name)
  File "/home/jenkins/miniconda/envs/goodman_focus/lib/python3.7/unittest/loader.py", line 377, in _get_module_from_name
    __import__(name)
  File "/var/lib/jenkins/workspace/GoodmanFocus/goodman_focus/tests/test_goodman_focus.py", line 9, in <module>
    from ccdproc import CCDData
  File "/home/jenkins/miniconda/envs/goodman_focus/lib/python3.7/site-packages/ccdproc/__init__.py", line 16, in <module>
    from .core import *
  File "/home/jenkins/miniconda/envs/goodman_focus/lib/python3.7/site-packages/ccdproc/core.py", line 12, in <module>
    from astropy.extern import six
ImportError: cannot import name 'six' from 'astropy.extern' (/home/jenkins/miniconda/envs/goodman_focus/lib/python3.7/site-packages/astropy/extern/__init__.py)


----------------------------------------------------------------------
Ran 3 tests in 0.000s

FAILED (errors=3)
Test failed: <unittest.runner.TextTestResult run=3 errors=3 failures=0>
error: Test failed: <unittest.runner.TextTestResult run=3 errors=3 failures=0>
Build step 'Execute shell' marked build as failure
Sending e-mails to: storres@ctio.noao.edu simonneftali@gmail.com
Finished: FAILURE
```

**Comment by simontorres** [comment]
Just checked the master branch in github and the line `from astropy.extern import six` has been removed, is there date when version `2.1.1` is going to be released?

**Comment by mwcraig** [comment]
> Just checked the master branch in github and the line from astropy.extern import six has been removed, is there date when version 2.1.1 is going to be released?

I'll try to get it out in the next hour since this is a bad break...

**Comment by saimn** [comment]
`astropy.extern.six` was removed long time ago (#619) so 2.1.0 should already be fine, are you sure you are using this version ?

**Comment by mwcraig** [comment]
> astropy.extern.six was removed long time ago (#619) so 2.1.0 should already be fine, are you sure you are using this version ?

I can't find `six` in 2.1 (which is good news :)

**Comment by simontorres** [comment]
I tested with astropy 4.0 and and ccdproc 2.1.0 and it failed. I will check again just in case

**Comment by mwcraig** [comment]
It looks like you are trying to create a python 3.8 environment 

```
+ conda env create -q python=3.8 -f environment.yml
```

but later on it is importing stuff from a 3.7 environment

```
  File "/home/jenkins/miniconda/envs/goodman_focus/lib/python3.7/unittest/loader.py", line 154, in loadTestsFromName
```

**Comment by simontorres** [comment]
just noticed that but ignored it. Thanks. My environment says it has ccdproc 2.1.0 but is loading 1.3.0.post1. :/

**Comment by simontorres** [comment]
I still have the 1.3.0.post1 version on my `setup.cfg`**sorry for the alarms!**

**Comment by mwcraig** [comment]
No worries, it just confirms that others rely on `ccdproc`, which is always welcome news 😀 

Closing, but please reopen if necessary.
